<script>
$( function() {
   $( "#datepicker" ).datepicker({dateFormat: "yy-mm-dd"});
 } );

var bookings = [];
$.getJSON('/api/booking/get', function(data){
  $.each(data, function (key, booking) {
    $('select#bookings').append($('<option></option>').attr('value', booking.id).text(booking.reason));
    bookings[booking.id] = booking;
  });

  $("select#bookings").change(function(){
    $('input#id').val(this.value);
    $('input#username').val(bookings[this.value].username);
    $('input#reason').val(bookings[this.value].reason);
    $('input#start_date').val(bookings[this.value].startdate);
    $('input#end_date').val(bookings[this.value].enddate);
  });
});

</script>
<select id="bookings">
<option value="">Please select... </option>
</select>

<form id="update" method="post" action = '/api/booking/update' />
  <input type="hidden" id="id" name="id" />
  Username: <input type="text" id="username" name="username" /><br />
  Reason: <input type="text" id="reason" name="reason" /><br />
  Start Date (YYYY-MM-DD HH:MM): <input type="text" id="start_date" name="start_date" /><br />
  End Date (YYYY-MM-DD HH:MM): <input type="text" id="end_date" name="end_date" /><br />
  <input type="submit" />
</form>
